Web API/Controllers/AccountwebController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using Web_API.Models;

namespace Web_API.Controllers
{
    public class AccountwebController : Controller
    {
        UserEntities1 db = new UserEntities1();
        

        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(Account p)
        {
            if (ModelState.IsValid==true)
            {

                HttpClient hc = new HttpClient();
                hc.BaseAddress = new Uri("https://localhost:44301//api/Products");
                var insertrec = hc.PostAsJsonAsync<Account>("Accounts", p);
                insertrec.Wait();
                var Saverec = insertrec.Result;
                if (Saverec.IsSuccessStatusCode)
                {
                    return RedirectToAction("Login");
                }
                else
                {
                    ViewBag.InsertMeassage = "<script>alert('not register succefully !!')</script>";
                }
            }
            
            return View(p);
        }
        public ActionResult Login()
        {
            return View();

        }


        [HttpPost]
        public ActionResult Login(Account s)
        {
            var User = db.Accounts.Where(model => model.Email == s.Email && model.Password == s.Password).FirstOrDefault();
            if (User != null)
            {

                Session["UserId"] = s.Id.ToString();
                Session["Username"] = s.Email.ToString();


                TempData["loginstatus"] = "<script>alert('login succefully !!')</script>";
                
                return RedirectToAction("Home1", "Home");

            }
            else
            {
                
                ViewBag.ErrorMeassage = "<script>alert('email and password does not match !!')</script>";
            }
            return View();
        }

    }

}

Web API/Views/Accountweb/Login.cshtml
@model Web_API.Models.Account

@{
    ViewBag.Title = "Login";

    Layout = "~/Views/Shared/_Layout1.cshtml";

}

<h2>Login</h2>
@Html.Raw(TempData["Login"])

@Html.Raw(ViewBag.ErrorMeassage)

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">
        <h4></h4>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="login-page">
            <div class="form">
                <div class="login">
                    <div class="login-header">
                        <h3 style="text-align:center">LOGIN</h3>
                        <p style="text-align:center">Please enter your credentials to login.</p>
                    </div>
                </div>
                <div class="form-group">

                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Email" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">

                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", placeholder = "Password" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <input type="submit" value="Sign in" class="registerbtn" />
                <div style="margin-top:20px; text-align:center">
                    Don't have an account?@Html.ActionLink("Sign Up", "Register", "Account")
                </div>
            </div>
        </div>
    </div>

}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web API/Views/Accountweb/Register.cshtml
@model Web_API.Models.Account

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

@Html.Raw(ViewBag.InsertMeassage)
                


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="login-page">
            <div class="form" style="max-width: 500px">
                <div class="login">
                    <div class="login-header">
                        <h3 style="text-align:center; text-decoration:underline;">CREATE ACCOUNT</h3>


                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        Male
                        @Html.RadioButtonFor(model => model.Gender, "Male")
                        Female
                        @Html.RadioButtonFor(model => model.Gender, "Female")
                        @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Conform_Password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Conform_Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Conform_Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>


                <input type="submit" value="SignUp"  class="registerbtn " style="margin-left:70px" />


                <div style="text-align:center">
                    Already have an account?@Html.ActionLink("Sign in", "Login", "Accountweb")
                </div>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}